// app/layout.js
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Templates/Navbar";
import Footer from "./components/Templates/Footer";
import "aos/dist/aos.css"; // Import AOS CSS
import AOSInitializer from "./components/AOSInitializer"; // Import the AOS initializer
import Preloader from "./components/Preloader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolage.className}>
        <Preloader />
        <AOSInitializer /> {/* Initialize AOS */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
